# Use NodeJS server for the app
FROM node:18-alpine

WORKDIR /app

# Install dependencies first, as they change less often than code.
COPY package.json package-lock.json* ./
RUN npm install
COPY . .
RUN npx prisma generate
EXPOSE 80
RUN chmod +x migrate-and-start-dev.sh
CMD ["./migrate-and-start-dev.sh"]