# Use NodeJS server for the app
FROM node:18-alpine

WORKDIR /app

# Install dependencies first, as they change less often than code.
COPY package.json package-lock.json* ./
RUN npm install
COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev"]