export const textStyles = {
  "heading-4xl": {
    fontWeight: 600,
    fontSize: "4.5rem",
    lineHeight: "100%",
    letterSpacing: "0%",
  },
  "heading-3xl": {
    fontWeight: 600,
    fontSize: "3.75rem",
    lineHeight: "100%",
    letterSpacing: "0%",
  },
  "heading-2xl": {
    fontWeight: 600,
    fontSize: "3rem",
    lineHeight: "100%",
    letterSpacing: "0%",
  },
  "heading-xl": {
    fontWeight: 600,
    fontSize: "2.25rem",
    lineHeight: "120%",
    letterSpacing: "0%",
  },
  "heading-lg": {
    fontWeight: 600,
    fontSize: "1.875rem",
    lineHeight: "120%",
    letterSpacing: "0%",
  },
  "heading-md": {
    fontWeight: 600,
    fontSize: "1.25rem",
    lineHeight: "120%",
    letterSpacing: "0%",
  },
  "heading-sm": {
    fontWeight: 600,
    fontSize: "1rem",
    lineHeight: "120%",
    letterSpacing: "0%",
  },
  "heading-xs": {
    fontWeight: 600,
    fontSize: "0.875rem",
    lineHeight: "120%",
    letterSpacing: "0%",
  },
  "text-6xl": {
    fontWeight: 400,
    fontSize: "3.75rem",
    lineHeight: "150%",
    letterSpacing: "0%",
  },
  "text-5xl": {
    fontWeight: 400,
    fontSize: "3rem",
    lineHeight: "150%",
    letterSpacing: "0%",
  },
  "text-4xl": {
    fontWeight: 400,
    fontSize: "2.25rem",
    lineHeight: "150%",
    letterSpacing: "0%",
  },
  "text-3xl": {
    fontWeight: 400,
    fontSize: "1.875rem",
    lineHeight: "150%",
    letterSpacing: "0%",
  },
  "text-2xl": {
    fontWeight: 400,
    fontSize: "1.5rem",
    lineHeight: "150%",
    letterSpacing: "0%",
  },
  "text-xl": {
    fontWeight: 400,
    fontSize: "1.25rem",
    lineHeight: "150%",
    letterSpacing: "0%",
  },
  "text-lg": {
    fontWeight: 400,
    fontSize: "1.125rem",
    lineHeight: "150%",
    letterSpacing: "0%",
  },
  "text-md": {
    fontWeight: 400,
    fontSize: "1rem",
    lineHeight: "150%",
    letterSpacing: "0%",
  },
  "text-sm": {
    fontWeight: 400,
    fontSize: "0.875rem",
    lineHeight: "150%",
    letterSpacing: "0%",
  },
  "text-xs": {
    fontWeight: 400,
    fontSize: "0.75rem",
    lineHeight: "150%",
    letterSpacing: "0%",
  },
};
